apiVersion: v1
kind: Service
metadata:
  name: {{ include "apache-guacamole.guacamole.fullname" . }}
  labels:
    {{- include "apache-guacamole.labels" . | nindent 4 }}
spec:
  type: {{ .Values.guacamole.service.type }}
  ports:
  - port: {{ .Values.guacamole.service.port }}
    targetPort: {{ .Values.guacamole.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "apache-guacamole.selectorLabels" . | nindent 4 }}
    component: guacamole
